#!/bin/bash
#SBATCH --account=def-hpcg1725
#SBATCH --partition=reserved
#SBATCH --qos=privileged
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=1AtomDFTstrain0.75
#SBATCH --output=/global/home/hpc5146/Projects/SmallCellMTPTraining/SmallCellMTPTraining/activeLearning/test/1AtomDFTstrain0.75/1AtomDFTstrain0.75.run
#SBATCH --mem-per-cpu=4G
#SBATCH --time=0-0:20 # time (DD-HH:MM)
#SBATCH --wait

module load    StdEnv/2020  gcc/9.3.0  openmpi/4.0.3
module load    quantumespresso/6.6

cd /global/home/hpc5146/Projects/SmallCellMTPTraining/SmallCellMTPTraining/activeLearning/test/1AtomDFTstrain0.75

pw.x < 1AtomDFTstrain0.75.in > /global/home/hpc5146/Projects/SmallCellMTPTraining/SmallCellMTPTraining/activeLearning/testout/1AtomDFTstrain0.75.out
