
Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".


Activating Modules:
  1) CCconfig                 3) gentoo/2020          5) ucx/1.8.0
  2) flexiblascore/.3.0.4     4) libfabric/1.10.1

The following have been reloaded with a version change:
  1) StdEnv/2016.4 => StdEnv/2020           5) mii/1.1.1 => mii/1.1.2
  2) gcccore/.5.4.0 => gcccore/.9.3.0       6) openmpi/2.1.1 => openmpi/4.0.3
  3) imkl/11.3.4.258 => imkl/2020.1.217     7) r/3.5.0 => r/4.3.1
  4) java/1.8.0_121 => java/13.0.2

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
