#!/bin/bash
#SBATCH --account=def-hpcg1725
#SBATCH --partition=reserved
#SBATCH --qos=privileged
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=1
#SBATCH --job-name=test
#SBATCH --output=./test.run
#SBATCH --mem-per-cpu=4G
#SBATCH --time=0-0:03 # time (DD-HH:MM)
#SBATCH --wait

module load    cuda/11.6.1
module load       StdEnv/2020  gcc/9.3.0
module load openmpi/4.0.3

/usr/bin/time -o ./test.time -f "%e" mpirun -np 3 --oversubscribe  /global/home/hpc5146/mlip-3/bin/mlp select_add ./test.pot ./mtpTest.cfg ./preselected.cfg ./diff.cfg
